config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  get '/musicians/dashboard', to: 'musicians#dashboard', as: 'musicians_dashboard'

  resources :musicians, only: [:index, :show, :new, :create]
  resources :bands, only: [:index, :show]
  resources :venues, only: [:index, :show]
  resources :bookmark_boards, only: [:create]
  # resources :reviews, only: :create

  post '/musicians/:id/reviews', to: 'reviews#create', as: 'user_reviews'

  post '/requests', to: 'requests#create'
  patch '/requests/:id', to: 'requests#update_status', as: 'edit_status_requests'

  post '/chat_rooms/:chat_room_id/messages', to: 'messages#create', as: 'chat_room_messages'
  get '/chat_rooms/:id', to: 'chat_rooms#show', as: 'chat_room'

  mount ActionCable.server => "/cable"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/badge.rb
class Badge < ApplicationRecord
  belongs_to :review
  # belongs_to :user

  # belongs_to :from, :class_name => 'User', :foreign_key => 'from_id', optional: true
  # belongs_to :to, :class_name => 'User', :foreign_key => 'to_id', optional: true

  validates :badges, presence: true
  validates :stars, presence: true
end

app/models/band.rb
class Band < ApplicationRecord
  has_many :band_members
  has_many :users, through: :band_members
  has_many :bookmark_boards

  validates :band_name, uniqueness: { case_sensitive: false }
end

app/models/band_member.rb
class BandMember < ApplicationRecord
  belongs_to :user
  belongs_to :band
end

app/models/bookmark_board.rb
class BookmarkBoard < ApplicationRecord
  belongs_to :user
  belongs_to :band
  belongs_to :venue
end

app/models/chat_room.rb
class ChatRoom < ApplicationRecord
  has_many :messages, dependent: :destroy
end

app/models/equipment.rb
class Equipment < ApplicationRecord
  belongs_to :equipment_category

  validates :equipment_type, presence: true

  include PgSearch
  multisearchable against: [ :equipment_type, :syllabus ]
end

app/models/equipment_category.rb
class EquipmentCategory < ApplicationRecord
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :musician_genres
  has_many :users, through: :musician_genres
end

app/models/message.rb
class Message < ApplicationRecord
  after_create :broadcast_message

  belongs_to :chat_room
  belongs_to :band, optional: true
  belongs_to :user

  validates :content, presence: true, allow_blank: false

  def from?(some_user)
    user == some_user
  end

  def broadcast_message
    ActionCable.server.broadcast("chat_room_#{chat_room.id}", {
      message_partial: ApplicationController.renderer.render(
        partial: "messages/message",
        locals: { message: self, user_is_messages_author: false }
      ),
      current_user_id: user.id
    })
  end
end

app/models/musician_genre.rb
class MusicianGenre < ApplicationRecord
  belongs_to :genre
  belongs_to :user
end

app/models/request.rb
class Request < ApplicationRecord
  belongs_to :from, :class_name => 'User', :foreign_key => 'from_id', optional: true
  belongs_to :to, :class_name => 'User', :foreign_key => 'to_id', optional: true

  validates_uniqueness_of :from, :scope => [:to_id]

  STATUSES = ['pending', 'accepted', 'rejected', 'confirmed']
  validates :status, inclusion: { in: STATUSES, message: "%{value} is not a valid status" }
end

app/models/review.rb
class Review < ApplicationRecord
  # belongs_to :user
  # has_many :badges
  belongs_to :from, :class_name => 'User', :foreign_key => 'from_id', optional: true
  belongs_to :to, :class_name => 'User', :foreign_key => 'to_id', optional: true

  validates :content, presence: true
  validates :stars, presence: true
end

app/models/song.rb
class Song < ApplicationRecord
  belongs_to :genre, optional: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :from_requests, :class_name => 'Request', :foreign_key => 'from_id'
  has_many :to_requests, :class_name => 'Request', :foreign_key => 'to_id'

  has_many :equipment_musician_inventory
  has_many :equipments, through: :equipment_musician_inventory

  has_many :band_members
  has_many :bands, through: :band_members

  has_many :bookmark_boards

  has_many :musician_genres
  has_many :genres, through: :musician_genres

  has_many :from_reviews, :class_name => 'Review', :foreign_key => 'from_id'
  has_many :to_reviews, :class_name => 'Review', :foreign_key => 'to_id'

  mount_uploader :user_photo, PhotoUploader
  mount_uploader :banner_photo, PhotoUploader

  validates :fullname, presence: true
  validates :nickname, presence: true
  validates :location, presence: true

  include PgSearch
  multisearchable against: [ :location, :syllabus ]
end

app/models/venue.rb
class Venue < ApplicationRecord
  has_many :equipment_venue_inventory
  has_many :equipments, through: :equipment_venue_inventory

  has_many :venue_photos
  has_many :bookmark_boards
end

app/models/venue_photo.rb
class VenuePhoto < ApplicationRecord
  belongs_to :venue

  mount_uploader :photo, PhotoUploader
end

app/controllers/bands_controller.rb
class BandsController < ApplicationController
  def show
    @bookmark_boards = BookmarkBoard.first
    @band = Band.find(params[:id])
    authorize @band

    if ChatRoom.exists?(params[:id])
      @chat_room = ChatRoom.includes(messages: :user).find(params[:id])
    else
      @chat_room = ChatRoom.new(id: params[:id])
      @chat_room.save
    end

    @days = []
    # authorize @chat_room
  end

  def create_message
    @band = Band.find(params[:chat_room_id])
    @message = Message.new(message_params)
    authorize @message
    @chat_room = ChatRoom.find(params[:chat_room_id])
    @message.chat_room = @chat_room
    @message.user = current_user

    if @message.save
      respond_to do |format|
        format.html { redirect_to band_path(@band) }
        format.js
      end
    else
      respond_to do |format|
        format.html { render "chat_rooms/show" }
        format.js
      end
    end
  end

  private

  def message_params
    params.require(:message).permit(:content)
  end
end

app/controllers/musicians_controller.rb
class MusiciansController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]
  skip_after_action :verify_authorized, only: :show

  def index
    if params[:query].present?
      query = params[:query].downcase
      locations = policy_scope(User).where('lower(location) ILIKE ?', "%#{params[:query.downcase]}%")
      instrument = User.joins(:equipments).where("equipment_type ILIKE ?", "%#{params[:query.downcase]}%")
      @musicians = (locations + instrument).uniq
    else
      @musicians = policy_scope(User)
    end
  end

  def show
    @musician = User.find(params[:id])
    @musicians = User.all
    @request = Request.new



    # for connect form
    if user_signed_in?
      @requested = Request.find_by(from: current_user, to: @musician)
      @musicians_bands = current_user.bands.map { |band| [band.band_name, band.id] }
      @musicians_bands.unshift(['Form new band...', 0])
      @review = Review.new
      @reviews = Review.all.where('to_id = :user_id', { user_id: @musician.id })
      @badge = Badge.new
      @badges = Badge.all.where('to_id = :user_id', { user_id: @musician.id })
    end
  end

  def edit
    @musician = User.find(params[:id])
  end

  def update
    @musician = Restaurant.find(params[:id])
    @musician.update(params[musician_params])
  end

  def dashboard
    @musicians = User.all
    @musician = User.find(current_user.id)
    authorize @musician

    @from_requests = current_user.from_requests
    @to_requests = current_user.to_requests

    # @bands = current_user.bands.all
    @bands = current_user.bands

    @messages = Message.all.where('from_id = :user_id OR to_id = :user_id', { user_id: current_user.id })
  end

  def status_button_text(request)
    if current_user == request.to && request.status == 'pending'
      return 'accept'
    end
    if current_user == request.from && request.status == 'accepted'
      return 'confirm'
    end
  end
  helper_method :status_button_text

  private

  def musician_params
    params.require(:user).permit(:email, :user_photo)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home
  skip_after_action :verify_authorized, only: :home

  def home
    @musicians = User.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/musicians/dashboard.html.erb
<div class="dashboard-wrapper">
  <div class="musician">
    <div class="musician-d-container">
      <%= cl_image_tag(@musician.user_photo, class: 'dashboard_musician-image') %>
    </div>
    <div class="musician-d-nickname">
      <h3><%= @musician.nickname.capitalize %></h3>
    </div>
  </div>

  <div class="dashboard-profile">

    <input type="checkbox" style="display: none;" id="requests">
    <label for="requests" class="btn d-bands request" id="request-label">Request</label>
    <script>
      const request = document.getElementById('request-label')
      request.style.borderBottom = '4px solid #9745AF'
      $(document).ready(function() {
        $("#requests").change(function(){
          if(this.checked){
            $(".requests")[0].style.display = "block";
            $(".personal-information")[0].style.display = "none";
            $(".bands-feature")[0].style.display = "none";
            request.style.borderBottom = '4px solid #9745AF';
            profile.style.borderBottom = 'none';
            band.style.borderBottom = 'none';
          } else {
            $(".requests")[0].style.display = "block";
            $(".personal-information")[0].style.display = "none";
            $(".bands-feature")[0].style.display = "none";
            request.style.borderBottom = '4px solid #9745AF';
            band.style.borderBottom = 'none';
            profile.style.borderBottom = 'none';
          }
        })
      });
    </script>

    <input type="checkbox" style="display: none;" id="bands">
    <label for="bands" class="btn d-bands band" id='band-label'>Bands</label>
    <script>
      const band = document.getElementById('band-label')
      $(document).ready(function() {
        $("#bands").change(function(){
          if(this.checked){
            $(".bands-feature")[0].style.display = "block";
            $(".personal-information")[0].style.display = "none";
            $(".requests")[0].style.display = "none";
            band.style.borderBottom = '4px solid #3F5DFA'
            request.style.borderBottom = 'none';
            profile.style.borderBottom = 'none'
          } else {
            $(".bands-feature")[0].style.display = "block";
            $(".personal-information")[0].style.display = "none";
            $(".requests")[0].style.display = "none";
            request.style.borderBottom = 'none';
            profile.style.borderBottom = 'none'
            band.style.borderBottom = '4px solid #3F5DFA';
          }
        })
      });
    </script>

    <input type="checkbox" style="display: none;" id="profile">
    <label for="profile" class="btn d-bands profile" id='profile-label'>Profile</label>
    <script>
      const profile = document.getElementById('profile-label')
      $(document).ready(function() {
        $("#profile").change(function(){
          if(this.checked){
            $(".personal-information")[0].style.display = "block";
            $(".requests")[0].style.display = "none";
            $(".bands-feature")[0].style.display = "none";
            profile.style.borderBottom = '4px solid #E84369'
            request.style.borderBottom = 'none';
            band.style.borderBottom = 'none';
          } else {
            $(".personal-information")[0].style.display = "block";
            $(".bands-feature")[0].style.display = "none";
            $(".requests")[0].style.display = "none";
            profile.style.borderBottom = '4px solid #E84369';
            request.style.borderBottom = 'none';
            band.style.borderBottom = 'none';
          }
        })
      });
    </script>


  </div>

  <div class="personal-information" style='display: none; margin-bottom: 15vh;'>
    <div class="d-p-info">

      <div class="show-banner-overlay" style="border-top-left-radius: 20px;">
        <div class="absolute-banner-to-edit">
        <div class="show-banner" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= cl_image_path(@musician.banner_photo) %>'); border-top-left-radius: 20px;">
          <div class="musician-show-banner-content">
            <%= link_to edit_user_registration_path do %>
              <i class="fas fa-edit edit-icon"><span>Edit Profile</span></i>
            <% end %>
            <div class="show-nickname">
              <%= @musician.nickname.capitalize %>
            </div>
              <h4><%= @musician.tag_line %></h4>


            </div>
          </div>
        </div>
      </div>


      <div class="container">
        <div class="musicians-show-container">
          <div class="show-musician-pic-wrapper">
            <%= cl_image_tag(@musician.user_photo, class:"show-musician-photo") %>
            <div class="s-musician-pic-overlay"></div>
          </div>

          <div class="gray-detail-container">
            <div class="gray-info-contents">
              <div class="gray-name">
                <% @musician.fullname.split(' ').each do |m| %>
                  <%= m.capitalize %>
                <% end %>
              </div>
              <div class="gray-bio">
                <p ><%= @musician.description %></p>
              </div>
              <div class="gray-eq">
                <%
                  instruments = @musician.equipments.map do |e|
                    e.equipment_type.capitalize
                  end
                %>
                <%= instruments.join(" · ") %>
              </div>
              <div class="gray-other-info">
                <% unless @musician.genres.nil? %>
                  <p>Genre:
                    <%
                      genres = []
                      @musician.genres.each do |genre|
                        genres << genre.name
                      end
                    %>
                    <%= genres.join(' · ') %>
                  </p>
                <% end %>
                <p>Location: <%= @musician.location %></p>
              </div>

              <% unless @musician.bands.empty? %>
                <div class="gray-view-bands">
                  <p>Bands:</p>
                  <ul>
                    <% @musician.bands.each do |band| %>
                      <li><%= band.band_name.capitalize %></li>
                    <% end %>
                  </ul>
                </div>
              <% end %>

            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="requests" style="margin-bottom: 15vh;" >
<!--     <h3>Your Requests</h3>
 -->
      <div class="r-container">
        <div class="f-request">
          <h4 class="request-header">Sent Requests</h4>
          <div class="from-request"> <!-- adds bottom space
 -->
          <% if @from_requests.exists? %>
            <% @from_requests.each do |r| %>
              <div class="r-card">
                  <p>Status : <%= r.status.capitalize %></p>
                  <% @musicians.where(id: r.to_id).each do |m| %>
                    <%= link_to musician_path(m.id) do %>
                      <p class='r-card-nickname'>Request to : <%= m.nickname.capitalize! %></p>
                      <%= cl_image_tag(m.user_photo, class: 'r-img') %>
                    <% end %>
                    <p>Message : <%= r.message %></p>
                    <% if button_text = status_button_text(r) %>
                      <%= link_to button_text.capitalize, edit_status_requests_path(r), method: 'patch', class: "btn btn-primary" %>
                    <% end %>
                    <% unless r.status == 'confirmed' || r.status == 'rejected' %>
                      <%= link_to 'Reject', edit_status_requests_path(r, reject: 1), method: 'patch', class: "btn btn-danger" %>
                    <% end %>
                  <% end %>
              </div>
            <% end %>
          <% else %>
             <p style="padding: 35px;margin-left: 20px;">No requests you have send yet...</p>
          <% end %>

          </div>
        </div>

         <div class="to-request">
          <h4 class="request-header">Requests From Other Musicians</h4>
          <div class="r-t-container">
            <% if @to_requests.exists? %>
              <% @to_requests.each do |r| %>
                <div class="r-card">
                  <p>Status : <%= r.status.capitalize %></p>
                  <% @musicians.where(id: r.from_id).each do |m| %>
                    <%= link_to musician_path(m.id) do %>
                      <p class='r-card-nickname'>Request from : <%= m.nickname.capitalize! %></p>
                      <%= cl_image_tag(m.user_photo, class: 'r-img') %>
                    <% end %>
                  <% end %>
                  <p>Message : <%= r.message %></p>
                  <% if button_text = status_button_text(r) %>
                    <%= link_to button_text.capitalize, edit_status_requests_path(r), method: 'patch', class: "btn btn-success" %>
                  <% end %>
                  <% unless r.status == 'confirmed' || r.status == 'rejected' %>
                    <%= link_to 'Reject', edit_status_requests_path(r, reject: 1), method: 'patch', class: "btn btn-danger" %>
                  <% end %>
                </div>
              <% end %>
            <% else %>
               <p style="padding: 35px;margin-left: 20px;">No requests yet...</p>
            <% end %>
           </div>
         </div>

      </div>

  </div>


  <div class="bands-feature" style="display: none; margin-bottom: 15vh;">
    <h3 style="padding: 5px;font-family: 'open sans';font-weight: lighter;font-size: 25px;margin-bottom: 20px;margin-left: 35px;">Your Bands</h3>
    <div class="your-bands">
      <% if @bands.exists? %>
        <% @bands.each do |b| %>
          <%= link_to band_path(b) do %>
            <div class="b-card">

              <div style="background-image: linear-gradient(rgba(0,0,0,0.6),rgba(0,0,0,0.2)), url(https://res.cloudinary.com/harrisongarovi/image/upload/v1551851442/adult-artist-artists-210887.jpg); border-top-left-radius: 20px; width:100%; height:50%; background-size: cover; ">
                  <div class="dash-band-wrapper">
                    <div class= "dash-band-contents">
                      <p class='band-name'><%= b.band_name.capitalize %></p>
                      <p id='members'>Members</p>
                    </div>
                  </div>
              </div>
          <% end %>

              <div class="b-members-wrapper" style="margin-top: 35px;margin-left: 20px;">
              <% b.band_members.each do |m| %>
                  <% user = User.find(m.user_id) %>
                <div class="b-members">
                  <%= link_to musician_path(m.user_id) do %>
                    <%= cl_image_tag(user.user_photo, class: 'b-img') %>
                  <% end %>
                </div>
              <% end %>

              </div>
            </div>
          <% end %>
      <% else %>
        <p style='padding-left: 20px;'><%= 'No Bands formed yet... ' %></p>
      <% end %>
    </div>
  </div>

</div>

app/views/musicians/show.html.erb
<div class="show-banner-overlay">
    <div class="show-banner" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= cl_image_path(@musician.banner_photo) %>');">
      <div class="musician-show-banner-content">
        <div class="show-nickname">
          <%= @musician.nickname.capitalize %>
        </div>
          <h4><%= @musician.tag_line %></h4>
          <div class="badges">
            <% if @reviews %>
              <% badges = @reviews.map do |r| %>
                <% r.badges %>
              <% end %>
              <% badges.uniq.each do |u| %>
                <% unless u == nil  %>
                <p># <%= u %></p>
                <% end %>
              <% end %>
            <% else %>
              <%=  %>
            <% end %>
          </div>
      </div>
    </div>
</div>


<div class="s-container">
  <div class="musicians-show-container">
    <div class="show-musician-pic-wrapper">
      <%= link_to musician_path(@musician) do %>
      <%= cl_image_tag(@musician.user_photo, class:"show-musician-photo") %>
      <% end %>
      <div class="s-musician-pic-overlay">
      </div>
    </div>

    <div class="gray-detail-container">
      <div class="gray-info-contents">
        <div class="gray-name">
          <% @musician.fullname.split(' ').each do |m| %>
            <%= m.capitalize %>
          <% end %>
          <% if user_signed_in? && @musician != current_user %>
            <input type="checkbox" style="display: none;" id="invite">
            <label for="invite" class='btn btn-primary invite-btn'>Jam with <%= @musician.nickname.capitalize %></label>
          <% end %>
          <script>
            $(document).ready(function() {
              $("#invite").change(function(){
                if(this.checked){
                  $("#m-invite")[0].style.display = "block";
                  $('.m-show-description')[0].style.display = 'none';
                  $('.invite-btn')[0].style.display = 'none';
                  $('.m-review-b')[0].style.display = 'none';
                  document.querySelector('#last_review').style.display = 'none';
                } else {
                  $("#m-invite")[0].style.display = "none";
                }
              })
            });
          </script>

        </div>
        <div id="m-invite" style='display: none;'>
          <% if user_signed_in? && current_user != @musician %>

            <div id="connect">
              <% if @requested %>
                <div class="sent-r"><p><%= link_to "You have sent a request.", musicians_path, class: "text-center btn btn-secondary disabled align-center", :disabled => true %></p></div>
                <div><p><%= link_to 'Back', musician_path(@musician) %></p></div>
              <% else %>
                <div class="invite-form">
                  <%= simple_form_for @request, wrapper: :inline_form do |f| %>
                    <p><%= f.input :to_id, :as => :hidden, :input_html => { :value => @musician.id } %>
                    <%= f.input :band_id, collection: @musicians_bands, class: 'form-control select', selected: 0 %></p>
                    <p><%= f.input :message, placeholder: 'Message' %></p>
                    <p class='i-submit'><%= f.button :submit, 'Invite', class: "btn btn-success connect" %>
                    <%= link_to 'Back', musician_path(@musician), style: 'padding-left: 10px;' %></p>
                    <% end %>
                </div>
              <% end %>
            </div>
          <% end %>
        </div>

        <div class="m-show-description">
          <div class="gray-bio">
            <p ><%= @musician.description %></p>
          </div>
          <div class="gray-eq">
            <%
              instruments = @musician.equipments.map do |e|
                e.equipment_type.capitalize
              end
            %>
            <%= instruments.join(" · ") %>
          </div>
          <div class="gray-other-info">
            <% unless @musician.genres.nil? %>
              <p>Genre:
                <%
                  genres = []
                  @musician.genres.each do |genre|
                    genres << genre.name.capitalize
                  end
                %>
                <%= genres.join(' · ') %>
              </p>
            <% end %>
              <p>Location: <%= @musician.location.capitalize %></p>
          </div>

          <% unless @musician.bands.empty? %>
            <div class="gray-view-bands">
              <ps>Bands:
                <% @musician.bands.each do |band| %>
                  <%= band.band_name.capitalize %>
                <% end %></p>
            </div>
          <% end %>
        </div>



        <label for="m-review" class='btn m-review-b'>View Gig History</label>
        <input type="checkbox" style="display: none;" id="m-review">
        <script>
          $(document).ready(function() {
            $("#m-review").change(function(){
              if(this.checked){
                $(".musician-review")[0].style.display = "block";
                $(".m-show-description")[0].style.display = "none";
                $(".gray-name")[0].style.display = "none";
                $(".m-review-b")[0].style.display = "none";
                $("#m-invite")[0].style.display = "none";
                document.querySelector('#last_review').style.display = 'none';
              } else {
                $(".musician-review")[0].style.display = "none";
              }
            })
          });
        </script>
        <div class="r-last-review" id='last_review'>
          <% if @reviews %>
            <div class="last-review">
              <% 5.times.each do |count| %>
                <% if @reviews.last.stars && @reviews.last.stars > count %>
                  <i class="fas fa-star star"></i>
                <% else %>
                  <i class="fas fa-star unstar"></i>
                <% end %>
              <% end %>
              <p><%= @reviews.last.content %></p>
              <p class='review-from'>Comments from <%= @musicians.find(@reviews.last.from_id).nickname.capitalize %></p>
            <%# else %>
              <%#= 'No comments yet.' %>
            </div>
          <% end %>
        </div>

        <div class="musician-review" style='display: none;'>
          <div class="review-content">
            <% if @reviews %>
              <% @reviews.each do |r| %>
                <div class="r-content">
                  <% 5.times.each do |count| %>
                    <% if r.stars && r.stars > count %>
                      <i class="fas fa-star star"></i>
                    <% else %>
                      <i class="fas fa-star unstar"></i>
                    <% end %>
                  <% end %>
                  <p><%= r.content %></p>
                  <p class='review-from'>Comments from <%= @musicians.find(r.from_id).nickname.capitalize %></p>
                </div>
              <% end %>
              <% if @musician != current_user %>
                <input type="checkbox" style="display: none;" id="m-write-review">
                <label for="m-write-review" class='btn btn-primary write-btn'>Write comments</label>
                <div class='back-btn'><%= link_to 'Back', musician_path(@musician) %></div>
              <% end %>
              <div id="create-review" style="display: none">
                <%= simple_form_for [@musician, @review] do |f| %>
                  <%= f.input :content %>
                  <%= f.input :stars  %>
                  <%= f.input :badges, as: :select, collection: [ 'Awesome guitarist!', 'Great musician', 'Funky'] %>
                  <%= f.submit "Send", class: "btn btn-success review-submit" %>
                  <%#= flash.now[:notice] = "Review has been saved successfully." %>
                  <p class='write-btn'><%= link_to 'Back', musician_path(@musician) %></p>
                <% end %>
              </div>
            <% else %>
              <p class='no-comment'><%= 'No comments yet.' %></p>
              <input type="checkbox" style="display: none;" id="m-write-review">
              <label for="m-write-review" class='btn btn-primary write-btn'>Write the first comment!</label>
              <p class='back-btn'><%= link_to 'Back', musician_path(@musician) %></p>
              <script>
                document.querySelector("#m-write-review").addEventListener("click", function() {
                  console.log("clicked");
                  document.querySelector('#create-review').style.display = "block";
                  document.querySelector('.write-btn').style.display = "none";
                  document.querySelector('#m-invite').style.display = "none";
                  document.querySelector('.no-comment').style.display = "none";
                  document.querySelector('.back-btn').style.display = "none";
                })
              </script>
              <% if user_signed_in? %>
                <div id="create-review" style="display: none">
                  <%= simple_form_for [@musician, @review] do |f| %>
                    <%= f.input :content %>
                    <%= f.input :stars  %>
                    <%= f.input :badges, as: :select, collection: [ 'Awesome guitarist!', 'Great musician', 'Funky'] %>
                    <%= f.submit "Send", class: "btn btn-success review-submit" %>
                    <%#= flash.now[:notice] = "Review has been saved successfully." %>
                  <p><%= link_to 'Back', musician_path(@musician) %></p>
                  <% end %>
                </div>
              <% end %>
            <% end %>

        </div>
      </div>
    </div>
  </div>
</div>

              <script>
                document.querySelector("#m-write-review").addEventListener("click", function() {
                  document.querySelector('#create-review').style.display = "block";
                  document.querySelector('.write-btn').style.display = "none";
                  console.log(document.querySelector('.write-btn').style.display);
                  document.querySelector('.r-content').style.display = "none";
                  document.querySelector('.back-btn').style.display = "none";
                  document.querySelector('#last_review').style.display = 'none';
                })
              </script>