config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  get '/musicians/dashboard', to: 'musicians#dashboard', as: 'musicians_dashboard'

  resources :musicians, only: [:index, :show, :new, :create]
  resources :bands, only: [:index, :show]
  resources :venues, only: [:index, :show]
  resources :bookmark_boards, only: [:create]
  # resources :reviews, only: :create

  post '/musicians/:id/reviews', to: 'reviews#create', as: 'user_reviews'

  post '/requests', to: 'requests#create'
  patch '/requests/:id', to: 'requests#update_status', as: 'edit_status_requests'

  post '/chat_rooms/:chat_room_id/messages', to: 'messages#create', as: 'chat_room_messages'
  get '/chat_rooms/:id', to: 'chat_rooms#show', as: 'chat_room'

  mount ActionCable.server => "/cable"
end

app/models/band.rb
class Band < ApplicationRecord
  has_many :band_members
  has_many :users, through: :band_members
  has_many :bookmark_boards

  validates :band_name, uniqueness: { case_sensitive: false }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :from_requests, :class_name => 'Request', :foreign_key => 'from_id'
  has_many :to_requests, :class_name => 'Request', :foreign_key => 'to_id'

  has_many :equipment_musician_inventory
  has_many :equipments, through: :equipment_musician_inventory

  has_many :band_members
  has_many :bands, through: :band_members

  has_many :bookmark_boards

  has_many :musician_genres
  has_many :genres, through: :musician_genres

  has_many :from_reviews, :class_name => 'Review', :foreign_key => 'from_id'
  has_many :to_reviews, :class_name => 'Review', :foreign_key => 'to_id'

  mount_uploader :user_photo, PhotoUploader
  mount_uploader :banner_photo, PhotoUploader

  validates :fullname, presence: true
  validates :nickname, presence: true
  validates :location, presence: true

  include PgSearch
  multisearchable against: [ :location, :syllabus ]
end

app/controllers/bands_controller.rb
class BandsController < ApplicationController
  def show
    @bookmark_boards = BookmarkBoard.first
    @band = Band.find(params[:id])
    authorize @band

    if ChatRoom.exists?(params[:id])
      @chat_room = ChatRoom.includes(messages: :user).find(params[:id])
    else
      @chat_room = ChatRoom.new(id: params[:id])
      @chat_room.save
    end

    @days = []
    # authorize @chat_room
  end

  def create_message
    @band = Band.find(params[:chat_room_id])
    @message = Message.new(message_params)
    authorize @message
    @chat_room = ChatRoom.find(params[:chat_room_id])
    @message.chat_room = @chat_room
    @message.user = current_user

    if @message.save
      respond_to do |format|
        format.html { redirect_to band_path(@band) }
        format.js
      end
    else
      respond_to do |format|
        format.html { render "chat_rooms/show" }
        format.js
      end
    end
  end

  private

  def message_params
    params.require(:message).permit(:content)
  end
end

app/views/bands/_messages.html.erb
<div class="messages-container">
  <div class="row">
    <div class="col-sm-12">
      <% if @chat_room.nil? %>
        <div>No messages</div>
      <% else %>
        <div class="messages">
          <% @chat_room.messages.each do |message| %>
            <%
              date = message.created_at.strftime("%A, %b %d %Y")
              unless @days.nil?
                unless @days.include? date
                  @days << date
            %>
              <div class="message-date-container">
                <div class="message-line">
                  <div class="message-date">
                    <%= local_time(message.created_at, "%A, %b %d %Y") %>
                  </div>
                </div>
              </div>
              <% end %>
            <% end %>
            <%= render 'messages/message', message: message, user_is_messages_author: message.user == current_user %>
          <% end %>
        </div>
      <% end %>
      <div id="create-message">
        <%= simple_form_for [ @chat_room, Message.new ], remote: true, wrapper: :inline_form, html: { class: 'form-inline', autocomplete: 'off' } do |f| %>
          <%= f.input :content, label: false %>
          <%= f.submit "Send", class: "btn btn-success message-submit2" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

<% content_for :after_js do %>
  <script>
    scrollLastMessageIntoView();
    App['chat_room_<%= @chat_room.id %>'] = App.cable.subscriptions.create(
      { channel: 'ChatRoomsChannel', chat_room_id: <%= @chat_room.id %> },
      {
        received: (data) => {
          if (data.current_user_id !== <%= current_user.id %>) {
            document.querySelector('.messages').insertAdjacentHTML('beforeend', data.message_partial);
            scrollLastMessageIntoView();
          }
        }
      })
  </script>
<% end %>

app/views/bands/index.html.erb
<h1>Bands#index</h1>
<p>Find me in app/views/bands/index.html.erb</p>

app/views/bands/show.html.erb
<div class="show-banner" style="background-image: linear-gradient(rgba(0,0,0,0.6),rgba(0,0,0,0.2)), url(https://res.cloudinary.com/harrisongarovi/image/upload/v1551851442/adult-artist-artists-210887.jpg);">
  <div class="card-category-band">
    <div class="container">
      <div class="show-nickname" style="text-shadow: 0 2px 3px rgba(0, 0, 0, 0.5);">
        <%= @band.band_name.capitalize %>
      </div>
        <div style="display: flex; justify-content: center;">
        <% @band.band_members.all.each do |member|%>
         <%= link_to musician_path(member.user) do %>
        <span><%= cl_image_tag(member.user.user_photo, class:'member-avatar-banner')%></span>
        <% end %>
        <% end %>
        </div>
        <div class="banner-band-description">
        </div>
      </div>
    </div>
  </div>
</div>


<!-- <div class="container"> -->
  <div class="show-container">

    <div class="card-wrapper">
      <div class="card-contents-band">
        <p class='band-members-title' style="margin:0;">Members</p>
        <div class="band-members-wrapper">

          <% @band.band_members.all.each do |member|%>
              <div class="band-members">
                <%= link_to musician_path(member.user) do %>
                  <span><%= cl_image_tag(member.user.user_photo, class:'member-avatar')%></span>
                <% end %>
                <div class="member-description">
                  <strong><%= member.user.nickname.capitalize %></strong> plays
                    <% equipment = Equipment.find(member.user.equipment_ids).map do |instrument| %>
                      <% instrument.equipment_type.capitalize %>
                    <% end %>
                    <%= equipment.join(',') %>
                  <p style="color: black; opacity: 0.6">Location: <%= member.user.location.capitalize %></p>
                </div>
              </div>
          <% end %>
        </div>
      </div>

    <div class="bookmarked-venues-container">
      <!-- <div class="card-wrapper"> -->
        <div class="card-contents-band">
          <p class="book-venues">Venues List
          <%= link_to venues_path, class: 'venues_path' do %>
            <i class="fas fa-plus"></i>
          <% end %></p>
          <div class="venue-description">
            <% @band.bookmark_boards.each do |bookmark| %>
              <div class="bookmark-content">
                <div><%= cl_image_tag(bookmark.venue.venue_photos.first.photo, class: 'bookmark-venue-photo') %></div>
                <div class="bookmark-text">
                  <!-- <p class="venue-name">Venue name</p> -->
                  <%= link_to venue_path(bookmark.id) do %>
                    <h4 class="bookmark-name"><%= bookmark.venue.en_name %> </h4>
                  <% end %>
                  <p class='who-bookmarked'><%= bookmark.user.nickname.capitalize %> bookmarked</p>
                </div>
              </div>
          <% end %>

          </div>
        <!-- </div> -->
      </div>
    </div>
      <script>
        $(document).ready(function() {
          $("#connect").change(function(){
            if(this.checked){
              $(".popup")[0].style.display = "block";
              $(".card-contents")[0].style.display = "none";
            } else {
              $(".popup")[0].style.display = "none";
            }
          })
        });
      </script>



    </div>

    <div class="chat-container">
      <h3 style="margin-top: 0;">Messages</h3>
      <%= render 'messages' %>
    </div>


  </div>
<!-- </div> -->