config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  get '/musicians/dashboard', to: 'musicians#dashboard', as: 'musicians_dashboard'

  resources :musicians, only: [:index, :show, :new, :create]
  resources :bands, only: [:index, :show]
  resources :venues, only: [:index, :show]
  resources :bookmark_boards, only: [:create]
  # resources :reviews, only: :create

  post '/musicians/:id/reviews', to: 'reviews#create', as: 'user_reviews'

  post '/requests', to: 'requests#create'
  patch '/requests/:id', to: 'requests#update_status', as: 'edit_status_requests'

  post '/chat_rooms/:chat_room_id/messages', to: 'messages#create', as: 'chat_room_messages'
  get '/chat_rooms/:id', to: 'chat_rooms#show', as: 'chat_room'

  mount ActionCable.server => "/cable"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/badge.rb
class Badge < ApplicationRecord
  belongs_to :review
  # belongs_to :user

  # belongs_to :from, :class_name => 'User', :foreign_key => 'from_id', optional: true
  # belongs_to :to, :class_name => 'User', :foreign_key => 'to_id', optional: true

  validates :badges, presence: true
  validates :stars, presence: true
end

app/models/band.rb
class Band < ApplicationRecord
  has_many :band_members
  has_many :users, through: :band_members
  has_many :bookmark_boards

  validates :band_name, uniqueness: { case_sensitive: false }
end

app/models/band_member.rb
class BandMember < ApplicationRecord
  belongs_to :user
  belongs_to :band
end

app/models/bookmark_board.rb
class BookmarkBoard < ApplicationRecord
  belongs_to :user
  belongs_to :band
  belongs_to :venue
end

app/models/chat_room.rb
class ChatRoom < ApplicationRecord
  has_many :messages, dependent: :destroy
end

app/models/equipment.rb
class Equipment < ApplicationRecord
  belongs_to :equipment_category

  validates :equipment_type, presence: true

  include PgSearch
  multisearchable against: [ :equipment_type, :syllabus ]
end

app/models/equipment_category.rb
class EquipmentCategory < ApplicationRecord
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :musician_genres
  has_many :users, through: :musician_genres
end

app/models/message.rb
class Message < ApplicationRecord
  after_create :broadcast_message

  belongs_to :chat_room
  belongs_to :band, optional: true
  belongs_to :user

  validates :content, presence: true, allow_blank: false

  def from?(some_user)
    user == some_user
  end

  def broadcast_message
    ActionCable.server.broadcast("chat_room_#{chat_room.id}", {
      message_partial: ApplicationController.renderer.render(
        partial: "messages/message",
        locals: { message: self, user_is_messages_author: false }
      ),
      current_user_id: user.id
    })
  end
end

app/models/musician_genre.rb
class MusicianGenre < ApplicationRecord
  belongs_to :genre
  belongs_to :user
end

app/models/request.rb
class Request < ApplicationRecord
  belongs_to :from, :class_name => 'User', :foreign_key => 'from_id', optional: true
  belongs_to :to, :class_name => 'User', :foreign_key => 'to_id', optional: true

  validates_uniqueness_of :from, :scope => [:to_id]

  STATUSES = ['pending', 'accepted', 'rejected', 'confirmed']
  validates :status, inclusion: { in: STATUSES, message: "%{value} is not a valid status" }
end

app/models/review.rb
class Review < ApplicationRecord
  # belongs_to :user
  # has_many :badges
  belongs_to :from, :class_name => 'User', :foreign_key => 'from_id', optional: true
  belongs_to :to, :class_name => 'User', :foreign_key => 'to_id', optional: true

  validates :content, presence: true
  validates :stars, presence: true
end

app/models/song.rb
class Song < ApplicationRecord
  belongs_to :genre, optional: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :from_requests, :class_name => 'Request', :foreign_key => 'from_id'
  has_many :to_requests, :class_name => 'Request', :foreign_key => 'to_id'

  has_many :equipment_musician_inventory
  has_many :equipments, through: :equipment_musician_inventory

  has_many :band_members
  has_many :bands, through: :band_members

  has_many :bookmark_boards

  has_many :musician_genres
  has_many :genres, through: :musician_genres

  has_many :from_reviews, :class_name => 'Review', :foreign_key => 'from_id'
  has_many :to_reviews, :class_name => 'Review', :foreign_key => 'to_id'

  mount_uploader :user_photo, PhotoUploader
  mount_uploader :banner_photo, PhotoUploader

  validates :fullname, presence: true
  validates :nickname, presence: true
  validates :location, presence: true

  include PgSearch
  multisearchable against: [ :location, :syllabus ]
end

app/models/venue.rb
class Venue < ApplicationRecord
  has_many :equipment_venue_inventory
  has_many :equipments, through: :equipment_venue_inventory

  has_many :venue_photos
  has_many :bookmark_boards
end

app/models/venue_photo.rb
class VenuePhoto < ApplicationRecord
  belongs_to :venue

  mount_uploader :photo, PhotoUploader
end

app/controllers/bands_controller.rb
class BandsController < ApplicationController
  def show
    @bookmark_boards = BookmarkBoard.first
    @band = Band.find(params[:id])
    authorize @band

    if ChatRoom.exists?(params[:id])
      @chat_room = ChatRoom.includes(messages: :user).find(params[:id])
    else
      @chat_room = ChatRoom.new(id: params[:id])
      @chat_room.save
    end

    @days = []
    # authorize @chat_room
  end

  def create_message
    @band = Band.find(params[:chat_room_id])
    @message = Message.new(message_params)
    authorize @message
    @chat_room = ChatRoom.find(params[:chat_room_id])
    @message.chat_room = @chat_room
    @message.user = current_user

    if @message.save
      respond_to do |format|
        format.html { redirect_to band_path(@band) }
        format.js
      end
    else
      respond_to do |format|
        format.html { render "chat_rooms/show" }
        format.js
      end
    end
  end

  private

  def message_params
    params.require(:message).permit(:content)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home
  skip_after_action :verify_authorized, only: :home

  def home
    @musicians = User.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <%= favicon_link_tag 'apple-touch-icon-57x57.png', rel: 'apple-touch-icon-precomposed', type: 'image/png' %>
    <%= favicon_link_tag 'apple-touch-icon-114x114.png', rel: 'apple-touch-icon-precomposed', type: 'image/png' %>
    <%= favicon_link_tag 'apple-touch-icon-72x72.png', rel: 'apple-touch-icon-precomposed', type: 'image/png' %>
    <%= favicon_link_tag 'apple-touch-icon-144x144.png', rel: 'apple-touch-icon-precomposed', type: 'image/png' %>
    <%= favicon_link_tag 'apple-touch-icon-60x60.png', rel: 'apple-touch-icon-precomposed', type: 'image/png' %>
    <%= favicon_link_tag 'apple-touch-icon-120x120.png', rel: 'apple-touch-icon-precomposed', type: 'image/png' %>
    <%= favicon_link_tag 'apple-touch-icon-76x76.png', rel: 'apple-touch-icon-precomposed', type: 'image/png' %>
    <%= favicon_link_tag 'apple-touch-icon-152x152.png', rel: 'apple-touch-icon-precomposed', type: 'image/png' %>
    <%= favicon_link_tag 'favicon-196x196.png', type: 'image/png', sizes: '196x196' %>
    <%= favicon_link_tag 'favicon-96x96.png', type: 'image/png', sizes: '96x96' %>
    <%= favicon_link_tag 'favicon-32x32.png', type: 'image/png', sizes: '32x32' %>
    <%= favicon_link_tag 'favicon-16x16.png', type: 'image/png', sizes: '16x16' %>
    <%= favicon_link_tag 'favicon-128.png', type: 'image/png', sizes: '128x128' %>

    <!-- <title><%#= yield(:title) %></title> -->
    <title>C Major 7 - Connecting Musicians</title>
    <meta property="og:title" content="Connect with local musicians." />
    <meta property="og:description" content="Find local musicians to jam with at open mic venues. Search for guitarists, bassists, and drummers." />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="https://www.cmajor7.com/" />
    <meta property="og:image" content="https://www.cmajor7.com/homepage.png" />

    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro" rel="stylesheet">
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
    <%= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
    <link href="https://fonts.googleapis.com/css?family=Montserrat:900" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Josefin+Sans|Montserrat:900" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Signika" rel="stylesheet">
  </head>
  <body>
    <%= render 'page-elements/navbar' %>

    <%= yield %>

    <%= render 'page-elements/footer' %>
    <%= javascript_pack_tag 'application' %>
    <%= javascript_include_tag 'application' %>
    <%= yield :after_js %>
  </body>
</html>

app/views/page-elements/_footer.html.erb
<div class="footer">

  <div class="footer-top-items">
    <div class="footer-logo">
      <%= link_to root_path do %>
        <%= image_tag 'whitelogo.PNG', alt: "logo", height: 40, width: 60  %>
      <% end %>
      <%= link_to root_path do %>
        <div class="footer-logo-title">
          Cmaj7
        </div>
      <% end %>
    </div>
  </div>

  <div class="footer-bottom-items">
    <div class="footer-item">
      <a href="#"><i class="fab fa-instagram fa-2x"></i></a>
      <a href="#"><i class="fab fa-facebook fa-2x"></i></a>
      <a href="#"><i class="fab fa-twitter fa-2x"></i></a>
    </div>

    <div class="footer-text", sans-serif;">
      C Major 7 was made with <i class="fas fa-heart"></i> by Yuki, Harrison, Chris, and Kumi
    </div>
  </div>
</div>

app/views/page-elements/_navbar.html.erb
<div class="navbar-wagon navbar-logo">
  <!-- Logo -->

  <div class="logo-h1">
    <div style="margin-left: 58px">
    <%= link_to root_path do %>
      <%= image_tag 'logo2.PNG', alt: "logo", height: 40, width: 60  %>
    <% end %>
    </div>
    <%= link_to root_path do %>
    <h1 class="logo-h1 h1" style="margin-bottom: 20px; color: white; font-family:'Josefin Sans', sans-serif; font-weight: 900; font-size: 25px">
      Cmaj7
    </h1>
    <% end %>
  </div>

  <div class="navbar-right">
  <% if user_signed_in? %>
  <!--   <div class= "navbar-item navbar-link">Hello, <%= current_user.nickname.capitalize %></div> -->
    <input type="checkbox" style="display: none;" id="search">
    <label for="search" class='btn search-btn'>
      <i class="fas fa-search awesome-search-color fa-lg"></i>
    </label>

    <script>
      $(document).ready(function() {
        $("#search").change(function(){
          if(this.checked){
            $(".musician-search-bar")[0].style.display = "block";
            $('.search-btn')[0].style.display = 'none'
          } else {
            $(".musician-search-bar")[0].style.display = "none";
          }
        })
      });
    </script>

    <div class="flex-grow-3 d-flex musician-search-bar" style="display: none">
      <%= form_tag musicians_path, method: :get, class: 'search-form' do %>
        <!-- <div style="width: 20px; height: 35px; background-color: #E84369; border-top-left-radius: 15px; border-bottom-left-radius: 15px;"></div> -->
        <%= text_field_tag :query, params[:query], class: "form-home mr-sm-6 search-field", placeholder: " Search by instrument or location" %>
        <%= button_tag(type: "submit", class: "btn search-btn") do %>
           <i class="fas fa-search awesome-search-color fa-lg"></i>
        <% end %>
      <% end %>
    </div>

    <%= link_to "Musicians", musicians_path, class: "navbar-item musician-navbar-link"%>
    <%= link_to "Venues", venues_path, class: "navbar-item venue-navbar-link" %>
    <div class="navbar-wagon-item">
      <div class="dropdown">
        <% if current_user.user_photo.blank? %>
          <%= image_tag "https://via.placeholder.com/50/", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", data: {toggle: "dropdown"} %>
        <% else %>
          <%= cl_image_tag(current_user.user_photo, width: 50, class: "avatar dropdown-toggle", id: "navbar-wagon-menu", data: {toggle: "dropdown"}) %>
        <% end %>

        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <li><%= link_to "Dashboard", musicians_dashboard_path %></li>
          <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
        </ul>
      </div>
    </div>
  <% else %>
    <div class="navbar-wagon-item">
      <%= link_to "Musicians", musicians_path, class: "navbar-item musician-navbar-link" %>
      <%= link_to "Venues", venues_path, class: "navbar-item venue-navbar-link" %>
      <%= link_to "Log in", new_user_session_path, class: "navbar-item nav-sl-navbar-link" %>
      <%= link_to "Sign up", new_user_registration_path, class: "navbar-item nav-sl-navbar-link" %>
    </div>
  <% end %>
  </div>

</div>

app/views/pages/home.html.erb
<% content_for :title, "C Major 7" %>

<div class="landing-page">

<div class="landing-banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://res.cloudinary.com/harrisongarovi/image/upload/v1552020765/audience-band-blur-1587927.jpg);">

  <div class="container">
    <div class="lading-banner-container">
      <div class="lading-banner-word">
        <h1 style="font-size: 200px; font-weight: bold; margin-top: 0;">Let's Play.</h1>
         <h2 style="font-weight: bold; margin: 0;">Jam with the local community.</h2>
          <div class="expore-button-wrapper">
            <%= link_to "Explore", musicians_path, class: "explore-button" %>
          </div>
      </div>
    </div>
  </div>
</div>

<div class="down-arrow-icon">
  <input type="checkbox" style="display: none;" id="scroll">
  <label for="scroll" class="scroll-down"><i class="fas fa-chevron-down fa-3x"></i></label>
  <script>
    $("#scroll").click(function() {
      $([document.documentElement, document.body]).animate({
          scrollTop: $(".header").offset().top
      }, 2000);
    });
  </script>
</div>

<div class="landing-white-section">
  <h1 class="header" style="display: flex; justify-content: center;">
    <div style="margin-bottom: 50px; border-bottom: 5px solid #E84369; width: 900px; padding-bottom: 10px;">
      A social network for musicians, by musicians.
    </div>
  </h1>

  <div style="justify-content: space-between;align-items: center;align-content: center;display: flex;margin: 0px 191px;">
    <div class="landing-white-contents"">
      <div class="scj-icons">
       <i class="fas fa-search fa-3x"></i>
      </div>
      <h2 style="font-size: 24px; font-weight: bold; font-family: 'open sans'; text-align: center;  padding-bottom: 10px; margin-top: 10px">Search</h2>
      <p style="width: 180px; margin-bottom: 0;">Search for musicians seeking others to jam and perform with.</p>
    </div>

    <div class="landing-white-contents">
      <div class="scj-icons">
       <i class="fas fa-user-friends fa-3x"></i>
      </div>
      <h2 style="font-size: 24px; font-weight: bold; font-family: 'open sans'; padding-bottom: 10px; margin-top: 10px">Connect</h2>
      <p style="width: 180px; margin-bottom: 0;">Connect and form a band over your shared passion of music.</p>
    </div>

    <div class="landing-white-contents">
      <div class="scj-icons">
       <i class="fas fa-music fa-3x"></i>
      </div>
      <h2 style="font-size: 24px; font-weight: bold; font-family: 'open sans'; padding-bottom: 10px; margin-top: 10px">Jam!</h2>
       <p style="width: 180px; margin-bottom: 0;">Meet up, jam, or perform at a select venue.</p>
    </div>
  </div>
</div>

<div class="explore-musician-title">
    <div class="g-exolore">
     <div class='explore-musician'>Featured Musicians</div>
    </div>
</div>

<div class="landing-musicians">

  <div class="card-container">

    <div class="musician-container">
      <div class="row">
        <% @musicians[0..2].each do |musician| %>
          <div class="col-xs-12 col-md-4">
            <% p musician %>
            <div class="musician-index">
              <div class="musician-card">
                <%= link_to musician_path(musician) do %>
                  <%= cl_image_tag(musician.user_photo, class: 'musician-image') %>

                  <div class="musician-description-shadow">
                  <div class="musician-card-description">
                  <p class="nickname">
                  <% unless musician.nickname.nil? %>
                    <%= musician.nickname.capitalize! %>
                  <% else %>
                    <%= musician.fullname %>
                  <% end %>
                  </p>

                  <div class="form-inline musician-equipment">
                    <%
                      instruments = []
                      musician.equipments.each do |e|
                        instruments << e.equipment_type.capitalize
                      end
                    %>
                    <%= instruments.join(" | ") %>
                  </div>
                  <p class="tag-line"><%= musician.tag_line %></p>
                  <p class="location">Location :  <%= musician.location.capitalize! %></p>

                </div>
                </div>

                <% end %>
              </div>
            </div>
          </div>
        <% end %>
      </div>
      <%= link_to musicians_path do %>
        <div class="more-explore-flex">
          <div class="more-explore">View all musicians</div>
        </div>
      <% end %>
    </div>
  </div>
</div>
</div>
</div>